server:
  port: 2222
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    secure-port-enabled: false   # enable https, caused certificate exception no subject alternative names present for LoadBalancing
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/,http://localhost:8762/eureka/