server:
  port: 9411
spring:
  application:
    name: zipkin-server
  cloud:
    stream:
      bindings:
        input:
          destination: sleuth
          binder: kafka
          group: zipkin_server
      kafka:
        binder:
          brokers: 10.200.159.84:9092
          zk-nodes: 10.200.159.84:2181
          auto-add-partitions: false
          auto-create-topics: false

eureka:
  client:
    service-url:
      defaultZone: http://10.200.157.6:8762/eureka/,http://10.200.157.6:8763/eureka/

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: 916815587139:click-test-es
      hosts: http://search-click-test-es-m6u6mo27fr7cqno2tdf5sgpx3m.us-west-2.es.amazonaws.com:80
      # Seems index prefix?
      index: tracer_log
      # Default setting of index, mind do not comment in the same line of property
      index-shards: 5
      index-replicas: 1
      # aws:
      #   domain:
      #   region:
