server:
  port: 9411
spring:
  application:
    name: zipkin-server

eureka:
  client:
    service-url:
      defaultZone: http://10.200.157.6:8762/eureka/,http://10.200.157.6:8763/eureka/

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: log-es
      hosts: http://host:port
      # Seems index prefix?
      index: tracer_log
      # Default setting of index, mind do not comment in the same line of property
      index-shards: 5
      index-replicas: 1
      # aws:
      #   domain:
      #   region:
