server:
  port: 9411
spring:
  application:
    name: zipkin-server-es
  cloud:
    stream:
      bindings:
        # Name of channel
        input:
          # Target destination of a channel, e.g. Topic of kafka
          destination: sleuth
          binder: kafka
          # Consumer group, if null, will be anonymous consumer
          group: zipkin_server
      # Configuration name of each binder, here use kafka as default
      kafka:
        binder:
          brokers: 10.200.159.84:9092
          zk-nodes: 10.200.159.84:2181
          auto-add-partitions: false
          auto-create-topics: false

eureka:
  client:
    service-url:
      defaultZone: http://10.200.157.6:8762/eureka/,http://10.200.157.6:8763/eureka/

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: log-es
      hosts: http://host:port
      # Seems index prefix?
      index: tracer_log
      # Default setting of index, mind do not comment in the same line of property
      index-shards: 5
      index-replicas: 1
      # aws:
      #   domain:
      #   region:
