# avoid incorrectly claiming info, heartbeat
# without these, health check ins invalid
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    secure-port-enabled: false   # enable https
    # instance-id: ${spring.application.name}
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/