eureka:
  #instance:
  #  hostname: localhost
  #  prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: false   # do not register itself as a client
    #healthcheck:
    #  enabled: true
    service-url:      # in many guidance, this property was serviceUrl, which will go wrong and pick for default 8761 server
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka-server-peer:8762/eureka/
  server:
   # 关闭Eureka自我保护机制, this mode cause Eureka to halt all de-registrations if drop below 85% threshold in 15 min
    enable-self-preservation: false  # turn off to avoid some warning, cause another warning
    wait-time-in-ms-when-sync-empty: 0 # default, speedup startup
    eviction-interval-timer-in-ms: 1000   # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）