# Eureka server provides info of apps and nodes
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    secure-port-enabled: false   # enable https, caused certificateexception no subject alternative names present for LoadBalancing
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/,http://localhost:8762/eureka/

zuul:
  ribbon-isolation-strategy: semaphore    # default isolation pattern is semaphore, another choice is THREAD if preferred
  host:                                   # Both are default value
    max-per-route-connections: 20
    max-total-connections: 200
#  filter:
#    pre:
#      path: com.yang.filter.pre
#  routes:
#    compute-supplier:
#      url: http://localhost:8080

# ribbon is invalid
#ribbon:
#  eureka:
#    enabled: false