# avoid incorrectly claiming info, heartbeat
# without these, health check ins invalid
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    secure-port-enabled: false   # enable https, caused certificateexception no subject alternative names present for LoadBalancing
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/,http://localhost:8762/eureka/

zuul:
  routes:
    compute-supplier:
      url: http://localhost:8080
# ribbon is invalid
#ribbon:
#  eureka:
#    enabled: false