eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true   # do not register itself as a client
    healthcheck:
      enabled: true
    serverUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka-server:8761/eureka/
  server:
   # 关闭Eureka自我保护机制, this mode cause Eureka to halt all de-registrations if drop below 85% threshold in 15 min
    enable-self-preservation: false  # turn off to avoid some warning, cause another warning
    wait-time-in-ms-when-sync-empty: 0 # default, speedup startup